default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "default_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "default_password") %>
  host: localhost


development:
  <<: *default
  database: blog_api_development

test:
  <<: *default
  database: blog_api_test


production:
  primary: &primary_production
    <<: *default
    database: blog_api_production
    username: blog_api
    password: <%= ENV["BLOG_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: blog_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: blog_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: blog_api_production_cable
    migrations_paths: db/cable_migrate
